@c -*- mode: texinfo; coding: utf-8 -*-
@c This is part of the GNU Guile-CV Reference Manual.
@c Copyright (C) 2023 Free Software Foundation, Inc.
@c See the file guile-cv.texi for copying conditions.


@node Histogram
@subsection Histogram

Other Guile-CV histogram procedures and methods.


@subheading Procedures


@ifhtml
@indentedblock
@table @code
@item @ref{im-histogram}
@end table
@end indentedblock
@end ifhtml


@anchor{im-histogram}
@deffn Procedure im-histogram image @
       [#:subtitle @quotedblleft{}Untitled@quotedblright{}]

Returns two values: (1) an image; (2) a list (or a list of list) of
significant values for @var{image}: one list if @var{image} is GRAY, a
list of list of values per channel if @var{image} is RGB.

The returned image is composed of a header (title, @var{#:subtitle}),
either the GRAY or the RGB channel histogram(s) for @var{image} and a
footer, which is a table containg, for each channel, the following
values: @code{mean}, @code{standard deviation}, @code{minimum},
@code{maximum}, the @code{mode}@footnote{The mode is the integer
corresponding to the histogram entry that received the maximum of hits,
and the value displayed in parens precisely is the number of hits.}
followed by its @code{value}.

Here below, the call sequence and the histogram for the GRAY image
@file{sinter.png} given along with Guile-CV documentation and examples:

@lisp
scheme@@(guile-user)> (im-load "sinter.png")
$32 = (212 128 1 (#f32(25.0 39.0 50.0 52.0 51.0 45.0 # …)))
scheme@@(guile-user)> (im-histogram $32 #:subtitle "sinter.png")
$34 = (282 271 1 (#f32(255.0 255.0 255.0 255.0 255.0 # …)))
$35 = (27136 163.346 75.081 0 243 215 727)
@end lisp

@ifnottex
@indentedblock
@image{images/sinter-histogram,,,sinter-histogram,png}
@end indentedblock
@end ifnottex

Note that histogram images returned by @code{im-histogram} have no
borders, the above histogram has been padded - using @code{(im-padd $34
1 1 1 1 #:color '(96 96 96))} - for better readability, otherwise the
title above and the table below would look as if they were not
centered.
@end deffn
