@c -*- mode: texinfo; coding: utf-8 -*-
@c This is part of the GNU Guile-CV Reference Manual.
@c Copyright (C) 2016 - 2023 Free Software Foundation, Inc.
@c See the file guile-cv.texi for copying conditions.


@node Utilities
@subsection Utilities

Other Guile-CV utility procedures, methods and variables.


@subheading Procedures

@ifhtml
@indentedblock
@table @code
@item @ref{im-display}
@item @ref{im-display-channel}
@item @ref{im-show}
@end table
@end indentedblock
@end ifhtml


@subheading Variables

@ifhtml
@indentedblock
@table @code
@item @ref{%image-cache}
@item @ref{%image-cache-format}
@end table
@end indentedblock
@end ifhtml


@subheading Procedures

@anchor{im-display}
@anchor{im-display-channel}
@deffn Procedure im-display image @
       [#:proc #f] [#:port (current-output-port)]
@deffnx Procedure im-display-channel channel width height @
        [#:proc #f] [#:port (current-output-port)]

Returns nothing.

Displays the content of @var{image} or @var{channel} on @var{port}.

The optional @var{#:proc} keyword argument must either be @code{#f}, the
default, or a procedure that accepts a single (32 bits float)
argument. When @var{#:proc} is @code{#f}, @code{im-display} will use an
internally defined procedure which formats its argument @samp{à la
octave}: nine positions, six decimals, all number aligned on the
dot. any value @code{>= 1000} is converted to use the exponential float
notation.  Here is an @samp{hand made} example:

@lisp
...
$2 = (4 3 3 (#f32(0.0 1.0 2.0 3.0 4.0 5.0) ... ...)
scheme@@(guile-user)> (im-divide $2 99)
$3 = (4 3 3 (#f32(10.1010103225708 0.010101010091602802 …) …))
scheme@@(guile-user)> (im-set! $3 0 0 0 10000)
$4 = (4 3 3 (#f32(10000.0 0.010101010091602802 # # # # …) …))
scheme@@(guile-user)> (im-display $4)
@print{}

Channel 1

     1.0E+4    0.01010    0.02020    0.03030
    0.04040    0.05051    0.06061    0.07071
    0.08081    0.09091    0.10101    0.11111

Channel 2

    0.12121    0.13131    0.14141    0.15152
    0.16162    0.17172    0.18182    0.19192
    0.20202    0.21212    0.22222    0.23232

Channel 3

    0.24242    0.25253    0.26263    0.27273
    0.28283    0.29293    0.30303    0.31313
    0.32323    0.33333    0.34343    0.35354
@end lisp

@strong{Caution:} unless you specify @var{port}, both this and
@ref{im-display-channel} procedures are meant to be used on very small
and testing images, otherwise even on a small image, it might be ok in a
terminal, but it will definitely will kill your emacs.
@end deffn

@anchor{im-show}
@deffn Method im-show filename
@deffnx Method im-show image [scale #f]
@deffnx Method im-show image name [scale #f]

Returns the string "#<Image: @dots{}>", where "@dots{}" is
either @var{filename} or a filename constructed by im-show, see below.

The optional @var{scale} argument can take the following values:

@indentedblock
@table @code
@item #f
pixel values are @samp{clipped}: values @code{< 0} are saved as
@code{0}, values @code{> 255} are saved as @code{255}, and otherwise are
saved unchanged

@item #t
all pixel values are scaled@footnote{Note that in this particular
context, @code{scale} does not mean a change in dimension, but rather
bringing pixel values from the range they occupy in memory to the
@code{[0 255]} range} to the @code{[0 255]} range
@end table
@end indentedblock

These three methods will also effectively dislay the image if you are
using @uref{@value{UGEISER}, Geiser}, which analyzes Guile's procedures
and methods returned values (through the use of its pattern matcher),
and when appropriate, triggers its image display mechanism.

Geiser has two variables that allow you to choose either to inline
images in its @uref{@value{UEMACS}, Emacs} (Guile repl) buffer, or to
display them using externel viewer: @code{geiser-image-viewer} and
@code{geiser-repl-inline-images-p}.  You may choose to add these
variables in your @file{.emacs} file, for example:

@example
(setq geiser-image-viewer "eog")
(setq geiser-repl-inline-images-p nil)
@end example

Note that @code{(setq geiser-repl-inline-images-p t)} will only work if
you are using a graphics-aware Emacs, and otherwise, will fall on the
external viewer approach, if the variable @code{geiser-image-viewer} has
been defined. When using Geiser in a non graphics-aware Emac, or when
using the external viewer approach, images will appear as buttons: press
return on them to invoke (or raise) the external viewer (window
containing that image).

Except for the first @code{im-show} method, Guile-CV has to save the
@var{image} first, and does it in the location defined by the
@ref{%image-cache} variable. If you call @code{im-show} passing
@var{name}, the @var{image} is saved as
@file{%image-cache/@var{name}.png}, otherwise under a generated name,
the result of @code{(symbol->string (gensym "im-show-"))}.

Note that if you do not specify @var{name}, a new external viewer window
is opened at each @code{im-show} invocation, even for identical
@var{image} calls: this because in Guile-CV, on purpose, images are just
list, with no (unique) identifier, and there is no way for
@code{im-show} to know ... Further to this point, when you pass
@var{name} as an argument, you are not @samp{identifying} @var{image},
which may actually differ, but rather just ask to reuse the filename and
hence the external viewer window associated with it.

Last note: many external viewers, such as Eog (the Gnome Eye Viewer),
will try to apply, per default, some sort of smoothing techniques,
especially on @code{zoom-in} and @code{zoom-out}: where this is fine for
viewing @samp{lazer} pictures, you probably want to check and disable
these options when working with Guile-CV.
@end deffn


@subheading Variables

@anchor{%image-cache}
@defvr Variable %image-cache
@cindex User Configuration

Specifies the location used by @ref{im-show} to save images. 

The default value is @file{/tmp/<username>/guile-cv}, but you may
@code{set!} it.  If you'd like to reuse that location for future
guile-cv sessions, you may save it in guile-cv's @samp{per user} config
file @file{<userdir>/.config/guile-cv} as an assoc pair, here is an
example:

@example
cat ~/.config/guile-cv.conf
((image-cache . "~/tmp"))
@end example

Note that if used, the @samp{~} is expanded at load time, so in geiser,
it becomes:

@example
scheme@@(guile-user)> ,use (cv)
scheme@@(guile-user)> %image-cache
@print{}
$2 = "/home/david/tmp"
@end example
@end defvr


@anchor{%image-cache-format}
@defvr Variable %image-cache-format

Specifies the format used by @ref{im-show} to save images. 

The default value is @code{"png"}, but you may @code{set!} it.  If you'd
like to reuse that format for future guile-cv sessions, you may save
it in guile-cv's @samp{per user} config file
@file{<userdir>/.config/guile-cv}, as an assoc pair, here is an
example:

@example
cat ~/.config/guile-cv.conf
((image-cache-format . "jpg"))
@end example
@end defvr
